server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://localhost:5431/schedulerdb
    username: admin
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

